//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserResult()
        {
            this.UserAnswers = new HashSet<UserAnswer>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdTest { get; set; }
        public Nullable<bool> IsPassed { get; set; }
        public Nullable<System.TimeSpan> TimeBegin { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserAnswer> UserAnswers { get; set; }
    }
}
